name: Go

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: "cr.selcloud.ru/mgomed"
  IMAGE_NAME: "chat-service"
  CONTAINER_NAME: "chat-service-container"
  MIGRATOR_IMAGE_NAME: "chat-migrator"
  MIGRATOR_CONTAINER_NAME: "chat-migrator-container"
  DB_IMAGE_NAME: "postgres:14-alpine3.17"
  DB_CONTAINER_NAME: "chat-db-container"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.23'
            cache-dependency-path: go.sum

        - name: Build
          run: go build -o ./bin/ -v ./...

        - name: Test
          run: go test -v ./...

  linter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61

          args: --timeout=30m --config=./.golangci.pipeline.yaml

  image-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file for CI
        run: |
          echo "DB_HOST=$DB_CONTAINER_NAME" >> build/.env
          echo "DB_PORT=5433" >> build/.env
          echo "POSTGRES_DB=chat" >> build/.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> build/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> build/.env
          echo "MIGRATION_DIR=./migrations" >> build/.env
          echo "SERVER_HOST=0.0.0.0" >> build/.env
          echo "SERVER_PORT=50052" >> build/.env
          echo "LOG_OUT_DIR=./out/log" >> build/.env

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

      - name: Build and Push auth-service Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME -f build/Dockerfile.app .

      - name: Build and Push auth-service Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --tag $REGISTRY/$MIGRATOR_IMAGE_NAME:$TAG_NAME -f build/Dockerfile.migrations build
  
  deploy-image:
    runs-on: ubuntu-latest
    needs: image-build-and-push

    steps:
      - name: Deploy to Selectel Cloud via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME,DB_CONTAINER_NAME,DB_IMAGE_NAME,MIGRATOR_CONTAINER_NAME,MIGRATOR_IMAGE_NAME
          script: |
            # Set up variables
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)

            # Login into Selectel Registry
            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

            # Create Docker network for containers
            docker network create chat-network || true
            
            # Stop and remove old chat-service container
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true

            # Stop and remove old chat-migrator container
            docker stop $MIGRATOR_CONTAINER_NAME || true
            docker rm $MIGRATOR_CONTAINER_NAME || true

            # Stop and remove old chat-db container
            docker stop $DB_CONTAINER_NAME || true
            docker rm $DB_CONTAINER_NAME || true

            # Start db container
            docker run -d --name $DB_CONTAINER_NAME \
            --network chat-network \
            -e POSTGRES_DB=chat \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -v chat_data:/var/lib/postgresql/data \
            -p 5433:5432 $DB_IMAGE_NAME

            # Create .env file for migrator
            echo "DB_PORT=5433" >> .env
            echo "POSTGRES_DB=chat" >> .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "MIGRATION_DIR=./migrations" >> .env

            # Start migrator container
            docker run -d --name $MIGRATOR_CONTAINER_NAME \
            --network chat-network \
            --env-file .env \
            -e DB_HOST=$DB_CONTAINER_NAME \
            -t $REGISTRY/$MIGRATOR_IMAGE_NAME:$TAG_NAME

            # Start chat-service container
            docker run -d --name $CONTAINER_NAME \
            --network chat-network \
            -p 50052:50052 \
            -t $REGISTRY/$IMAGE_NAME:$TAG_NAME ./app -config-path .env
            
            # Prune Docker images older than 24 hours
            docker image prune -a --filter "until=24h" -f
